Repository algosup/2024-2025-project-1-fpga-team-6, pull requests merged in 2024-10, with the labels that each got.

#6 Weekly merging
  3DModels/controller_case.STL
  3DModels/controller_case_cover.STL
  Documents/FunctionalSpecifications/functionalSpecifications.md
  Documents/Management/WeeklyReports/cumulative.md
  Documents/Management/WeeklyReports/week3.md
  Documents/Management/projectCharter.md
  Documents/TechnicalSpecifications/Appendix/controllerSchematic.png
  Documents/TechnicalSpecifications/technicalSpecifications.md
Labels: documentation, enhancement

#7 Technical specifications
  README.md
Labels: documentation

#8 Code base merge
  .gitignore
  .sconsign.dblite
  Frogger/PIN.pcf
  Frogger/Sprites/car2_sprite.v
  Frogger/Sprites/car3_sprite.v
  Frogger/Sprites/frog_sprite.v
  Frogger/Sprites/grass_sprite.v
  Frogger/Sprites/road_sprite.v
  Frogger/VGA/vga_color.v
  Frogger/VGA/vga_sync.v
  Frogger/apio.ini
  Frogger/bground_pixel.v
  Frogger/frog_movement.v
  Frogger/hardware.asc
  Frogger/hardware.bin
  Frogger/hardware.json
  Frogger/main.v
  Frogger/obj_pixel.v
  Frogger/switch.v
Labels: enhancement, code

#9 Documents
  Documents/Management/WeeklyReports/cumulative.md
  Documents/Management/WeeklyReports/week4.md
  Documents/Management/projectCharter.md
  Documents/Manuals/froggerGameManual.pdf
  Documents/Manuals/lilypadUserManual.pdf
  Documents/QA/Images/test-criteria.png
  Documents/QA/Images/test_case_pattern.png
  Documents/QA/Images/test_report_pattern.png
  Documents/QA/TestCases.md
  Documents/QA/TestPlan.md
  Documents/QA/TestReports.md
  Documents/TechnicalSpecifications/technicalSpecifications.md
Labels: documentation

#10 Pull Request
  Frogger/main.v
Labels: enhancement, code

#11 Update TestPlan.md
  Documents/QA/TestPlan.md
Labels: documentation, enhancement

#12 Final Documents merge
  Documents/Management/WeeklyReports/cumulative.md
  Documents/Management/WeeklyReports/week5.md
  Documents/Management/managementArtifacts.md
  Documents/Management/projectCharter.md
Labels: documentation, enhancement
